--Bài 4--

--Câu 11--
ALTER TABLE HOCVIEN ADD CONSTRAINT CHK_TUOI CHECK (YEAR(GETDATE()) - YEAR(NGSINH) >=18)

--Câu 12--
ALTER TABLE GIANGDAY ADD CONSTRAINT CHK_GD CHECK (TUNGAY < DENNGAY)

--Câu 13--
ALTER TABLE GIAOVIEN ADD CONSTRAINT CHK_TUOICUAGV CHECK (YEAR(GETDATE()) - YEAR(NGSINH) >=22)

--Câu 14--
SELECT *FROM MONHOC
WHERE ABS(TCLT - TCTH) > 3;
