--Bài 6--

--Cáu 1--
SELECT MAHV, CONCAT(HO, ' ', TEN) AS HOTEN, NGSINH, MALOP
FROM HOCVIEN
WHERE MAHV IN ('K1108', 'K1205', 'K1305')

--Câu 2--
SELECT  HOCVIEN.MAHV, HO, TEN, KETQUATHI.LANTHI, KETQUATHI.DIEM
FROM HOCVIEN

--Câu 3--
SELECT HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN, TENMH
FROM HOCVIEN
JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
JOIN MONHOC ON KETQUATHI.MAMH = MONHOC.MAMH
WHERE (KETQUATHI.LANTHI = 1 AND KETQUATHI.KQUA = 'Dat')

--Câu 4--
SELECT HOCVIEN.MAHV, HO, TEN
FROM HOCVIEN
JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE (KETQUATHI.MAMH = 'CTRR' AND KETQUATHI.LANTHI = 1 AND KETQUATHI.KQUA = 'Khong Dat')

--Câu 5--
SELECT MAHV, HO, TEN
FROM HOCVIEN
WHERE MAHV LIKE 'K%' 
AND MAHV IN (
					SELECT MAHV
					FROM KETQUATHI
					WHERE (MAMH = 'CTRR' AND KQUA = 'Khong Dat' AND LANTHI = 3)
				)